### ISSUE TITLE
api-ts-rest-express: typecheck fails — @ts-rest/express drags in @types/express@4, clashes with v5 Router

### ISSUE THREAD

**Issue by rtorcato** [rtorcato/api-common#201]
## Symptom

`pnpm -r typecheck` fails in `@rtorcato/api-ts-rest-express`:

```
packages/api-ts-rest-express/src/index.ts(53,3): error TS2345:
Argument of type '...@types+express@5.0.6/.../IRouter' is not assignable
to parameter of type '...@types+express@4.17.25/.../IRouter'.
```

Reproduce:

```sh
pnpm --filter @rtorcato/api-ts-rest-express typecheck
```

## Root cause

Two `@types/express` majors resolve in the same compile:

- The package/app declare `@types/express@^5` (our code uses Express 5 Router types).
- `@ts-rest/express` pins `@types/express@^4` internally, and its exported
  types reference the **4.x** `IRouter`. At the `s.router(...)` call site
  (`src/index.ts:53`) TS compares our 5.x Router against ts-rest's 4.x Router
  and they're structurally incompatible.

So it's a transitive types-version clash, not a bug in our code.

## Options

- Pin/alias `@types/express` to a single major across the tree
  (pnpm `overrides`), if ts-rest tolerates 5.x types at runtime.
- Adapt/cast at the ts-rest boundary in `src/index.ts` so the two Router
  types don't meet.
- Track upstream: `@ts-rest/express` supporting Express 5 `@types`.

## Context

- Pre-existing — **not** caused by #199 / PR #200; surfaced during that PR's
  full-workspace typecheck run.
- Only `api-ts-rest-express` is affected; every other package typechecks clean.

**Comment by rtorcato** [comment]
🤖 *Automated — `ai-issue-loop` implementer handoff. Posted under the owner's account by an agent; not a human message. There is no separate GitHub account for AI agents, so this appears under @rtorcato's avatar.*

## To lift this hold

The agent never got as far as the bug — it could not **reproduce** it, because the loop's worktree setup can't support a package-level typecheck. Nothing in the repo was modified. Pick one:

| Option | What happens |
|---|---|
| Give the worktree a real install | `rm` the `node_modules` symlink in `../api-common-worktrees/ai-201-ts-rest-express-typecheck` and run `pnpm install` there, then re-add `ai-ready`. Costs a full duplicate `node_modules`. |
| Fix the loop's harness first | Stop symlinking `node_modules` for package-level issues (docs-only issues are fine). Then re-add `ai-ready`. |
| Do this one by hand | The root cause is already diagnosed in the issue body; the remaining work is a judgement call an agent shouldn't make alone — see below. |

<details><summary>Why the agent could not reproduce it</summary>

The loop creates each worktree with `node_modules` symlinked to the main checkout. That shares only the **root** `node_modules` — but pnpm workspaces keep the resolution that matters in each package's own `packages/<name>/node_modules`, and those are not symlinked and do not exist in a fresh worktree.

Measured: the main checkout has per-package `node_modules` in **37 of 37** packages; the worktree had **1**.

So `pnpm --filter @rtorcato/api-ts-rest-express typecheck` there fails with `Cannot find module`, not the `TS2345` Router clash this issue describes. The agent correctly declined to force `pnpm install` (which wanted to purge and rebuild the shared modules dir) while other agents were mid-run against that same tree.

This is a defect in the loop's setup, not in this issue. Docs-only issues (#208, #224) were unaffected, which is why it surfaced only now.

</details>

<details><summary>The judgement call still waiting on a human</summary>

Even with a working reproduction, the candidate fixes are not equivalent and differ in blast radius: a pnpm `overrides`/`resolutions` entry, a `@types/express` devDependency pin, or a local type shim. On a **published** package whose `@ts-rest/express` peer range is consumer-visible, which of those is acceptable is a semver/policy decision. Related: #89 tracks bumping the `@ts-rest` peer to `^3.53` when stable, which may make this moot.

</details>
